version: '3.1'

services:
  db:
    image: postgres:16-alpine
    container_name: weather-forecast-db
    restart: always
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: weather
    ports:
      - "5432:5432"
