version: '3.1'

services:
  db:
    image: postgres:16-alpine
    container_name: weather-forecast-db
    restart: always
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: weather
    ports:
      - "5432:5432"
  backend:
    image: weather-forecast-backend:0.1
    container_name: weather-forecast-backend
    build:
      dockerfile: backend.Dockerfile
    links:
      - db
    depends_on:
      - db
  web:
    image: weather-forecast-web:0.1
    container_name: weather-forecast-web
    build:
      dockerfile: web.Dockerfile
    ports:
      - "80:80"
    links:
      - backend
